# Variational Bayesian Inference for Gaussian Mixture

Dataset: https://www.kaggle.com/datasets/ananta/credit-card-data?resource=download

## Importing the required libraries

In [7]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.mixture import BayesianGaussianMixture 
from sklearn.preprocessing import normalize, StandardScaler 
from sklearn.decomposition import PCA

## Loading and Cleaning the data

In [8]:
# Loading the Data 
df = pd.read_csv('dataset/CardBase.csv') 
df

             Card_Number Card_Family  Credit_Limit  Cust_ID
0    8638-5407-3631-8196     Premium        530000  CC67088
1    7106-4239-7093-1515        Gold         18000  CC12076
2    6492-5655-8241-3530     Premium        596000  CC97173
3    2868-5606-5152-5706        Gold         27000  CC55858
4    1438-6906-2509-8219    Platinum        142000  CC90518
..                   ...         ...           ...      ...
495  4708-4407-9601-6022     Premium        691000  CC64993
496  6042-2856-7280-2925        Gold         33000  CC26787
497  8706-3809-5167-3899     Premium        144000  CC32532
498  9540-8558-5897-5046     Premium        830000  CC90246
499  5587-7265-8118-7718        Gold         24000  CC37803

[500 rows x 4 columns]

In [9]:
# Dropping the Cust_ID column from the data 
df = df.drop('Cust_ID', axis = 1) 

# Handling the missing values 
df.fillna(method ='ffill', inplace = True) 
df.head()

C:\Users\Hp\AppData\Local\Temp\ipykernel_7624\831671015.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method ='ffill', inplace = True)

           Card_Number Card_Family  Credit_Limit
0  8638-5407-3631-8196     Premium        530000
1  7106-4239-7093-1515        Gold         18000
2  6492-5655-8241-3530     Premium        596000
3  2868-5606-5152-5706        Gold         27000
4  1438-6906-2509-8219    Platinum        142000

## Loading and Cleaning the data

In [10]:
# Scaling the data to bring all the attributes to a comparable level 
scaler = StandardScaler() 
X_scaled = scaler.fit_transform(df) 

# Normalizing the data so that the data 
# approximately follows a Gaussian distribution 
X_normalized = normalize(X_scaled) 

# Converting the numpy array into a pandas DataFrame 
X_normalized = pd.DataFrame(X_normalized) 

# Renaming the columns 
X_normalized.columns = df.columns 
X_normalized.head()

ValueError: could not convert string to float: '8638-5407-3631-8196'